; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.41"

; Modules
projects[views_bulk_operations][version] = ""

projects[admin_menu][version] = ""

projects[admin_views][version] = ""

projects[adminimal_admin_menu][version] = ""

projects[better_formats][version] = ""

projects[block_class][version] = ""

projects[book_title_override][version] = ""

projects[ctools][version] = ""

projects[ckeditor][version] = ""

projects[coffee][version] = ""

projects[colorbox][version] = ""

projects[colorizer][version] = ""

projects[crumbs][version] = ""

projects[facetapi][version] = ""

projects[date][version] = ""

projects[devel][version] = ""

projects[ds][version] = ""

projects[ds_bootstrap_layouts][version] = ""

projects[email][version] = ""

projects[entity][version] = ""

projects[entitycache][version] = ""

projects[entityreference][version] = ""

projects[field_formatter_class][version] = ""

projects[field_formatter_css_class][version] = ""

projects[field_formatter_settings][version] = ""

projects[field_group][version] = ""

projects[fontawesome][version] = ""

projects[panels][version] = ""

projects[image_resize_filter][version] = ""

projects[imce][version] = ""

projects[imce_filefield][version] = ""

projects[imce_mkdir][version] = ""

projects[imce_rename][version] = ""

projects[jquery_update][version] = ""

projects[l10n_update][version] = ""

projects[less][version] = ""

projects[libraries][version] = ""

projects[link][version] = ""

projects[mailjet][version] = ""

projects[masquerade][version] = ""

projects[module_filter][version] = ""

projects[noggin][version] = ""

projects[panels_ajax_tab][version] = ""

projects[panels_bootstrap_layouts][version] = ""

projects[paragraphs][version] = ""

projects[paragraphs_pack][version] = ""

projects[pathauto][version] = ""

projects[pdf][version] = ""

projects[replicate][version] = ""

projects[replicate_paragraphs][version] = ""

projects[rules][version] = ""

projects[scroll_to_top][version] = ""

projects[simple_timeline][version] = ""

projects[taxonomy_access][version] = ""

projects[taxonomy_access_fix][version] = ""

projects[taxonomy_manager][version] = ""

projects[taxonomy_menu_block][version] = ""

projects[term_reference_tree][version] = ""

projects[token][version] = ""

projects[variable][version] = ""

projects[transliteration][version] = ""

projects[url][version] = ""

projects[views][version] = ""

projects[views_bootstrap][version] = ""

projects[views_field_view][version] = ""

projects[views_term_hierarchy_weight_field][version] = ""

projects[views_tree][version] = ""

projects[webform][version] = ""

; Themes
projects[adminimal_theme][version] = ""

projects[bootstrap][version] = ""

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn
; and url is the url of the download.
libraries[fontawesome][download][type] = "git"
libraries[fontawesome][download][url] = "https://github.com/FortAwesome/Font-Awesome.git"
libraries[fontawesome][directory_name] = "fontawesome"
libraries[fontawesome][type] = "library"

libraries[CAS][download][type] = "get"
libraries[CAS][download][url] = "http://downloads.jasig.org/cas-clients/php/current.tgz"
libraries[CAS][directory_name] = "CAS"
libraries[CAS][type] = "library"

libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.5.6/ckeditor_4.5.6_full.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

libraries[lessphp][download][type] = "get"
libraries[lessphp][download][url] = "https://github.com/oyejorge/less.php/archive/v1.7.0.9.zip"
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"

libraries[pdf.js][download][type] = "git"
libraries[pdf.js][download][url] = "https://github.com/mozilla/pdf.js.git"
libraries[pdf.js][directory_name] = "pdf.js"
libraries[pdf.js][type] = "library"

libraries[tika][download][type] = "get"
libraries[tika][download][url] = "http://archive.apache.org/dist/tika/tika-app-1.6.jar"
libraries[tika][directory_name] = "tika"
libraries[tika][type] = "library"

libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox/archive/1.x.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

