; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.41"

; Modules
projects[views_bulk_operations][version] = "3.3"

projects[admin_menu][version] = "3.0-rc5"

projects[admin_views][version] = "1.5"

projects[adminimal_admin_menu][version] = "1.7"

projects[better_formats][version] = "1.0-beta1"

projects[block_class][version] = "2.3"

projects[book_title_override][version] = "1.1"

projects[ctools][version] = "1.9"

projects[ckeditor][version] = "1.16"

projects[coffee][version] = "2.2"

projects[colorbox][version] = "2.10"

projects[colorizer][version] = "1.8"

projects[crumbs][version] = "2.3"

projects[facetapi][version] = "1.5"

projects[date][version] = "2.9"

projects[devel][version] = "1.5"

projects[ds][version] = "2.11"

projects[ds_bootstrap_layouts][version] = "1.1"

projects[email][version] = "1.3"

projects[entity][version] = "1.6"

projects[entitycache][version] = "1.5"

projects[entityreference][version] = "1.1"

projects[field_collection][version] = "1.0-beta10"

projects[field_formatter_class][version] = "1.1"

projects[field_formatter_css_class][version] = "1.3"

projects[field_formatter_settings][version] = "1.1"

projects[field_group][version] = "1.4"

projects[fontawesome][version] = "2.5"

projects[panels][version] = "3.5"

projects[image_resize_filter][version] = "1.16"

projects[imce][version] = "1.9"

projects[imce_filefield][version] = "1.1"

projects[imce_mkdir][version] = "1.0"

projects[imce_rename][version] = "1.3"

projects[jquery_update][version] = "2.7"

projects[l10n_update][version] = "1.1"

projects[less][version] = "3.0"

projects[libraries][version] = "2.2"

projects[link][version] = "1.3"

projects[mailjet][version] = "2.5"

projects[masquerade][version] = "1.0-rc7"

projects[module_filter][version] = "2.0"

projects[noggin][version] = "1.1"

projects[panels_ajax_tab][version] = "1.1"

projects[panels_bootstrap_layouts][version] = "3.0"

projects[paragraphs][version] = "1.0-rc4"

projects[paragraphs_pack][version] = "1.0-alpha5"

projects[pathauto][version] = "1.3"

projects[pdf][version] = "1.7"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.

projects[replicate][version] = "1.1"

projects[replicate_paragraphs][version] = "1.2"

projects[rules][version] = "2.9"

projects[scroll_to_top][version] = "2.1"

projects[simple_timeline][version] = "1.0"

projects[taxonomy_access][version] = "1.0"

projects[taxonomy_access_fix][version] = "2.3"

projects[taxonomy_manager][version] = "1.0"

projects[taxonomy_menu_block][version] = "1.4"

projects[term_reference_tree][version] = "1.10"

projects[token][version] = "1.6"

projects[transliteration][version] = "3.2"

projects[url][version] = "1.0"

projects[views][version] = "3.13"

projects[views_bootstrap][version] = "3.1"

projects[views_field_view][version] = "1.2"

projects[views_term_hierarchy_weight_field][version] = "1.2"

projects[views_tree][version] = "2.0"

projects[webform][version] = "4.12"

; Themes
projects[adminimal_theme][version] = "1.18"

projects[bootstrap][version] = "3.4"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[fontawesome][download][type] = ""
libraries[fontawesome][download][url] = ""
libraries[fontawesome][directory_name] = "fontawesome"
libraries[fontawesome][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[CAS][download][type] = ""
libraries[CAS][download][url] = ""
libraries[CAS][directory_name] = "CAS"
libraries[CAS][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[lessphp][download][type] = ""
libraries[lessphp][download][url] = ""
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[pdf.js][download][type] = ""
libraries[pdf.js][download][url] = ""
libraries[pdf.js][directory_name] = "pdf.js"
libraries[pdf.js][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tika][download][type] = ""
libraries[tika][download][url] = ""
libraries[tika][directory_name] = "tika"
libraries[tika][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"
